# Generated by Django 3.2.4 on 2021-06-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('description', models.CharField(max_length=50, verbose_name='')),
                ('city', models.CharField(max_length=50, verbose_name='')),
                ('country', models.CharField(max_length=50, verbose_name='')),
                ('latitude', models.IntegerField(verbose_name='')),
                ('longtitude', models.IntegerField(verbose_name='')),
                ('website', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
